export const PAY_WITH_CASH_REQUEST = 'PAY_WITH_CASH_REQUEST';
export const PAY_WITH_CASH_SUCCESS = 'PAY_WITH_CASH_SUCCESS';
export const PAY_WITH_CASH_FAIL = 'PAY_WITH_CASH_FAIL';
export const SET_PAY_WITH_CASH_RESPONSE_FOR_SNACK =
	'SET_PAY_WITH_CASH_RESPONSE_FOR_SNACK';
