import { ScaledSheet } from 'react-native-size-matters';

export const userDetailsStyles = ScaledSheet.create({
	oudsContainer: {
		marginTop: '17%',
		width: '85%',
		marginLeft: 'auto',
		marginRight: 'auto',
		marginBottom: '10%',
	},
	oudsTextContainer: {},
	oudsWelcomeText: {
		fontSize: '38@ms0.3',
		letterSpacing: 1.3,
		color: '#666666',
		marginBottom: '13@s',
	},
	oudsShortText: {
		fontSize: '14@ms0.3',
		color: '#666666',
	},
	oudsShortText2: {
		fontSize: '14@ms0.3',
		color: '#666666',
		marginTop: '8%',
	},
	oudsAsteriskText: {
		fontSize: '12@ms0.3',
		color: '#888888',
	},
	oudsCityInputBox: {
		flexDirection: 'row',
		flex: 1,
		flexWrap: 'wrap',
		paddingLeft: '20@ms',
		height: '52@ms',
		marginTop: '8%',
		borderWidth: 1,
		borderColor: '#109FDA',
		borderRadius: 10,
		padding: '10@ms',
		backgroundColor: 'white',
		shadowColor: '#000',
		elevation: 8,
	},
	oudsStateInputBox: {
		flexDirection: 'row',
		flex: 1,
		flexWrap: 'wrap',
		paddingLeft: '20@ms',
		height: '52@ms',
		marginTop: '8%',
		marginLeft: '5%',
		borderWidth: 1,
		borderColor: '#109FDA',
		borderRadius: 10,
		padding: '10@ms',
		backgroundColor: 'white',
		shadowColor: '#000',
		elevation: 8,
	},
	oudsFormContainer: {
		width: '100%',
	},
	oudsPhoneInputBox: {
		paddingLeft: '20@ms',
		height: '52@ms',
		marginTop: '8%',
		borderWidth: 1,
		borderColor: '#109FDA',
		borderRadius: 10,
		padding: '10@ms',
		backgroundColor: 'white',
		shadowColor: '#000',
		elevation: 8,
	},
	oudsContinueButton: {
		width: '100%',
		borderRadius: 10,
		marginTop: '30@ms',
		backgroundColor: '#109FDA',
		justifyContent: 'center',
		height: '54@ms',
		shadowColor: '#000',
		shadowOffset: {
			width: 0,
			height: 4,
		},
		shadowOpacity: 0.3,
		shadowRadius: 4.65,
		elevation: 8,
		marginBottom: 15,
	},
	oudsContinueButton_text: {
		color: '#fff',
		fontSize: '20@ms0.3',
		fontWeight: 'bold',
		textTransform: 'uppercase',
		letterSpacing: 1,
	},
	oudsRegionContainer: {
		flexDirection: 'row',
		flex: 1,
		flexWrap: 'wrap',
		justifyContent: 'space-between',
	},
	dropdownsRow: {
		flexDirection: 'row',
		width: '100%',
	},
	dropdownBtnStyle: {
		flexDirection: 'row',
		//paddingLeft: '20@ms',
		flex: 1,
		height: '52@ms',
		marginTop: '8%',
		borderWidth: 1,
		borderColor: '#109FDA',
		borderRadius: 10,
		padding: '10@ms',
		backgroundColor: 'white',
		shadowColor: '#000',
		elevation: 8,
	},
	dropdownBtnStyleDisabled: {
		opacity: 0.5,
		flexDirection: 'row',
		//paddingLeft: '20@ms',
		flex: 1,
		height: '52@ms',
		marginTop: '8%',
		borderWidth: 1,
		borderColor: '#109FDA',
		borderRadius: 10,
		padding: '10@ms',
		backgroundColor: 'white',
		shadowColor: '#000',
		elevation: 8,
	},
	dropdownBtnTxtStyleActive: {
		fontSize: '14@ms0.3',
		color: '#000',
		textAlign: 'center',
	},
	dropdownBtnTxtStyleInactive: {
		fontSize: '14@ms0.3',
		color: '#aaa',
		textAlign: 'center',
	},
	dropdownDropdownStyle: { backgroundColor: '#EFEFEF' },
	dropdownRowStyle: {
		backgroundColor: '#EFEFEF',
		borderBottomColor: '#C5C5C5',
	},
	dropdownRowTxtStyle: {
		color: '#444',
		textAlign: 'left',
	},
});
