export const ADD_TENANT_REQUEST = 'ADD_TENANT_REQUEST';
export const ADD_TENANT_SUCCESS = 'ADD_TENANT_SUCCESS';
export const ADD_TENANT_FAILURE = 'ADD_TENANT_FAILURE';
export const CLEAR_ADD_TENANT_MSG_ERROR = 'CLEAR_ADD_TENANT_MSG_ERROR';
