export const GET_OWNER_DASHBOARD_REQUEST = 'GET_OWNER_DASHBOARD_REQUEST';
export const GET_OWNER_DASHBOARD_SUCCESS = 'GET_OWNER_DASHBOARD_SUCCESS';
export const GET_OWNER_DASHBOARD_FAILURE = 'GET_OWNER_DASHBOARD_FAILURE';
