export const UPDATE_TENANT_REQUEST = 'UPDATE_TENANT_REQUEST';
export const UPDATE_TENANT_SUCCESS = 'UPDATE_TENANT_SUCCESS';
export const UPDATE_TENANT_FAIL = 'UPDATE_TENANT_FAIL';
export const CLEAR_UPDATE_TENANT_MSG_ERROR = 'CLEAR_UPDATE_TENANT_MSG_ERROR';
