export const GET_TENANT_DASHBOARD_REQUEST = 'GET_TENANT_DASHBOARD_REQUEST';
export const GET_TENANT_DASHBOARD_SUCCESS = 'GET_TENANT_DASHBOARD_SUCCESS';
export const GET_TENANT_DASHBOARD_FAILURE = 'GET_TENANT_DASHBOARD_FAILURE';
